### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by choonho** [spaceone-dev/plugin-aws-trusted-advisor-inven-collector#12]
2021-01-14T02:01:00.633379144Z 2021-01-14T02:01:00.625Z [INFO] tnx-0d6e8aa79166 Collector.collect (service.py:283) (REQEUST) => {"options": {}, "secret_data": "********", "filter": {}}
2021-01-14T02:01:01.488716091Z [ EXECUTOR START ]
2021-01-14T02:01:01.488810860Z @@@ TrustedAdvisorManager @@@
2021-01-14T02:01:01.489886445Z ** Trusted Advisor Start **
2021-01-14T02:01:56.056668361Z Trusted Advisor Finished 54.566707611083984 Seconds
2021-01-14T02:01:56.285257472Z TOTAL TIME : 54.7961630821228 Seconds
2021-01-14T02:01:58.422207063Z 2021-01-14T02:01:58.421Z [INFO] tnx-207b4ebcdaae Collector.collect (service.py:283) (REQEUST) => {"options": {}, "secret_data": "********", "filter": {}}
2021-01-14T02:01:59.271170177Z [ EXECUTOR START ]
2021-01-14T02:01:59.271195269Z @@@ TrustedAdvisorManager @@@
2021-01-14T02:01:59.271519174Z ** Trusted Advisor Start **
2021-01-14T02:02:12.261756222Z 2021-01-14T02:02:12.261Z [ERROR] tnx-207b4ebcdaae Collector.collect (service.py:250) (Error) => list index out of range
2021-01-14T02:02:12.261791547Z error_code = ERROR_UNKNOWN
2021-01-14T02:02:12.261795646Z status_code = INTERNAL
2021-01-14T02:02:12.261832245Z message = list index out of range Traceback (most recent call last):
2021-01-14T02:02:12.261836571Z File "/usr/local/lib/python3.8/site-packages/plugin_aws_trustedadvisor-1.1-py3.8.egg/spaceone/inventory/api/plugin/collector.py", line 33, in collect
2021-01-14T02:02:12.261839845Z for resource in collector_svc.list_resources(params):
2021-01-14T02:02:12.261842738Z File "/usr/local/lib/python3.8/site-packages/spaceone/core/service.py", line 274, in _generate_response
2021-01-14T02:02:12.261845458Z for response in response_iterator:
2021-01-14T02:02:12.261848399Z File "/usr/local/lib/python3.8/site-packages/plugin_aws_trustedadvisor-1.1-py3.8.egg/spaceone/inventory/service/collector_service.py", line 82, in list_resources
2021-01-14T02:02:12.261851651Z for resource in future.result():
2021-01-14T02:02:12.261854348Z File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
2021-01-14T02:02:12.261906737Z return self.__get_result()
2021-01-14T02:02:12.261909267Z File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
2021-01-14T02:02:12.261911483Z raise self._exception
2021-01-14T02:02:12.261913478Z File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
2021-01-14T02:02:12.261927827Z result = self.fn(*self.args, **self.kwargs)
2021-01-14T02:02:12.261929958Z File "/usr/local/lib/python3.8/site-packages/plugin_aws_trustedadvisor-1.1-py3.8.egg/spaceone/inventory/libs/manager.py", line 28, in collect_resources
2021-01-14T02:02:12.261932190Z resources.extend(self.collect_cloud_services(params))
2021-01-14T02:02:12.261934088Z File "/usr/local/lib/python3.8/site-packages/plugin_aws_trustedadvisor-1.1-py3.8.egg/spaceone/inventory/manager/trustedadvisor_manager.py", line 53, in collect_cloud_services
2021-01-14T02:02:12.261936210Z flagged_resources = self._merge_flagged_resources(check_id_data, check_result)
2021-01-14T02:02:12.261938234Z File "/usr/local/lib/python3.8/site-packages/plugin_aws_trustedadvisor-1.1-py3.8.egg/spaceone/inventory/manager/trustedadvisor_manager.py", line 104, in _merge_flagged_resources
2021-01-14T02:02:12.261940368Z data[headers[idx]] = res[idx]
2021-01-14T02:02:12.261942168Z IndexError: list index out of range
2021-01-14T02:02:12.261943984Z
2021-01-14T03:01:01.180995253Z 2021-01-14T03:01:01.180Z [INFO] tnx-621c983f9a1d Collector.collect (service.py:283) (REQEUST) => {"options": {}, "secret_data": "********", "filter": {}}
2021-01-14T03:01:02.039227551Z [ EXECUTOR START ]
2021-01-14T03:01:02.039370884Z @@@ TrustedAdvisorManager @@@
2021-01-14T03:01:02.040023533Z ** Trusted Advisor Start **
2021-01-14T03:02:05.691967967Z Trusted Advisor Finished 63.65178322792053 Seconds
2021-01-14T03:02:05.969771787Z TOTAL TIME : 63.93054676055908 Seconds
2021-01-14T03:02:09.742664330Z 2021-01-14T03:02:09.742Z [INFO] tnx-5076a34be85b Collector.collect (service.py:283) (REQEUST) => {"options": {}, "secret_data": "********", "filter": {}}
2021-01-14T03:02:10.584744088Z [ EXECUTOR START ]
2021-01-14T03:02:10.584780433Z @@@ TrustedAdvisorManager @@@
2021-01-14T03:02:10.586794340Z ** Trusted Advisor Start **
2021-01-14T03:02:21.820446232Z 2021-01-14T03:02:21.820Z [ERROR] tnx-5076a34be85b Collector.collect (service.py:250) (Error) => list index out of range
2021-01-14T03:02:21.820471190Z error_code = ERROR_UNKNOWN
2021-01-14T03:02:21.820474303Z status_code = INTERNAL
2021-01-14T03:02:21.820476425Z message = list index out of range Traceback (most recent call last):
2021-01-14T03:02:21.820478584Z File "/usr/local/lib/python3.8/site-packages/plugin_aws_trustedadvisor-1.1-py3.8.egg/spaceone/inventory/api/plugin/collector.py", line 33, in collect
2021-01-14T03:02:21.820480912Z for resource in collector_svc.list_resources(params):
2021-01-14T03:02:21.820482909Z File "/usr/local/lib/python3.8/site-packages/spaceone/core/service.py", line 274, in _generate_response
2021-01-14T03:02:21.820485127Z for response in response_iterator:
2021-01-14T03:02:21.820487011Z File "/usr/local/lib/python3.8/site-packages/plugin_aws_trustedadvisor-1.1-py3.8.egg/spaceone/inventory/service/collector_service.py", line 82, in list_resources
2021-01-14T03:02:21.820499957Z for resource in future.result():
2021-01-14T03:02:21.820502033Z File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
2021-01-14T03:02:21.820504436Z return self.__get_result()
2021-01-14T03:02:21.820506363Z File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
2021-01-14T03:02:21.820508311Z raise self._exception
2021-01-14T03:02:21.820510101Z File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
2021-01-14T03:02:21.820512143Z result = self.fn(*self.args, **self.kwargs)
2021-01-14T03:02:21.820514015Z File "/usr/local/lib/python3.8/site-packages/plugin_aws_trustedadvisor-1.1-py3.8.egg/spaceone/inventory/libs/manager.py", line 28, in collect_resources
2021-01-14T03:02:21.820516097Z resources.extend(self.collect_cloud_services(params))
2021-01-14T03:02:21.820518064Z File "/usr/local/lib/python3.8/site-packages/plugin_aws_trustedadvisor-1.1-py3.8.egg/spaceone/inventory/manager/trustedadvisor_manager.py", line 53, in collect_cloud_services
2021-01-14T03:02:21.820520203Z flagged_resources = self._merge_flagged_resources(check_id_data, check_result)
2021-01-14T03:02:21.820522131Z File "/usr/local/lib/python3.8/site-packages/plugin_aws_trustedadvisor-1.1-py3.8.egg/spaceone/inventory/manager/trustedadvisor_manager.py", line 104, in _merge_flagged_resources
2021-01-14T03:02:21.820524282Z data[headers[idx]] = res[idx]
2021-01-14T03:02:21.820526185Z IndexError: list index out of range

**Comment by jihyungSong** [comment]
It is an occurred error in the past (maybe) so this issue is closed. 
After that, we will create a new issue when an error occurs again.
